### ISSUE TITLE
SelectingItemsControl SelectedIndex extension returns SelectingItemsControl instead of <T>

### ISSUE THREAD

**Issue by najak3d** [AvaloniaUI/Avalonia.Markup.Declarative#10]
These methods need to return <T>, not SelectingItemsControl. 

   public static SelectingItemsControl SelectedIndex(this SelectingItemsControl control, Int32 value = default, ...) => ....

Otherwise, a statement like this one;

    ComboBox box =new ComboBox().SelectedIndex(0);

Will not compile.   Because it can't translates 'SelectingItemsControl' into 'ComboBox'.

This extension needs to be changed to:

    public static T SelectedIndex<T>(this T control, Int32 value = default, ...) where T : SelectingItemsControl => ...

I'm guessing there are more like this one.  It's just the first one I came across.

**Comment by gritsenko** [comment]
Oh! Fixing it, thanks. Sorry for such delay
