### ISSUE TITLE
Visual Designer Support?

### ISSUE THREAD

**Issue by najak3d** [AvaloniaUI/Avalonia.Markup.Declarative#14]
I'm not sure how difficult this would be, but adding Visual Designer support (where you can preview your form before running), would be very nice.  (As it's done with the AXAML now.)    If it can be done for AXAML, seems like it should be viable for the C# composition as well.  But I'm a noob; what do I know? :)

**Comment by gritsenko** [comment]
I'm not sure if anyone will want to implement this. Let's return to this issue after 15k stars ;)
