### ISSUE TITLE
Can't build sample project

### ISSUE THREAD

**Issue by cleissonalves** [AvaloniaUI/Avalonia.Markup.Declarative#18]
Visual Studio shows an error on MvvmSampleView class: 
>There is no argument given that corresponds to the required formal parameter 'viewModel'.

EDIT: 
Seems like creating an empty constructor solves it. Don't know if this is the best solution:

```csharp

public MvvmSampleView(MvvmSampleViewModel viewModel) : base(viewModel){}

```

But then it throws an exception related to the Buttons on MyCustomControl.cs when debugging:

>This exception was originally thrown at this call stack:
    [External Code]
    Avalonia.Markup.Declarative.ButtonExtensions.Command.AnonymousMethod__0() in ControlPropertyExtensions.Generated.cs
    Avalonia.Markup.Declarative.ControlPropertyExtensions._set<TControl>(TControl, System.Action) in ControlPropertyExtensions.cs
    Avalonia.Markup.Declarative.ButtonExtensions.Command(Avalonia.Controls.Button, Avalonia.Data.IBinding) in ControlPropertyExtensions.Generated.cs
    MyCustomControl.Build() in MyCustomControl.cs
    Avalonia.Markup.Declarative.ViewBase.Initialize() in ViewBase.cs
    Avalonia.Markup.Declarative.ViewBase.ViewBase(bool) in ViewBase.cs
    MyCustomControl.MyCustomControl() in MyCustomControl.cs
    AvaloniaMarkupSample.MainView.Build() in MainView.cs
    Avalonia.Markup.Declarative.ViewBase.Initialize() in ViewBase.cs
    ...
    [Call Stack Truncated]

**Comment by gritsenko** [comment]
thanks! fixed in latest commit
