### ISSUE TITLE
Create a nuget package for this library

### ISSUE THREAD

**Issue by Ombrelin** [AvaloniaUI/Avalonia.Markup.Declarative#19]

**Comment by timahrentlov** [comment]
Yes. That would be nice. Oh well :)

**Comment by gritsenko** [comment]
@Ombrelin hello! For now this package is available on "Avalonia all builds" nuget feed: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed#all-builds-feed

I will be back with update, when the package will be published on the main nuget.org feed

**Comment by cleissonalves** [comment]
As stated by @gritsenko,  for now you can get the package using the nightly feed source.

```bash
dotnet add package Avalonia.Markup.Declarative --source https://nuget-feed-nightly.avaloniaui.net/v3/index.json
```

**Comment by gritsenko** [comment]
@danwalmsley @maxkatz6 you are the last hope of humanity!

**Comment by maxkatz6** [comment]
@gritsenko it's live! https://www.nuget.org/packages/Avalonia.Markup.Declarative 🥳

**Comment by gritsenko** [comment]
> @gritsenko it's live! https://www.nuget.org/packages/Avalonia.Markup.Declarative 🥳

thank you so much bro!
