### ISSUE TITLE
Building example for .NET Framework 4.7.2

### ISSUE THREAD

**Issue by tebjan** [AvaloniaUI/Avalonia.Markup.Declarative#3]
Unfortunately, we cannot use the latest .NET in our application yet, we probably need several months to convert the whole codebase.

So I've made an attempt to build the repo and the demo project with visual studio and targeting net472: https://github.com/tebjan/Avalonia.Markup.Declarative/tree/dev/net472-compatibility

It compiles everything well after the changes in the commit, but the window is just white on startup. Could someone give me a hin on what could be missing in order to load the content? Thank a lot. And here is my commit diff, would be nice if someone could do a sanity check: https://github.com/tebjan/Avalonia.Markup.Declarative/commit/af1a88ddd650a3c2caefd532dcdd65d8fbd1bf8e

there are the steps I've done:
* delete glabal.json
* set entry point example project to net472
* removed new syntax from visual studio 2022 (global includes, file wide namespace)

**Comment by gritsenko** [comment]
just added test app https://github.com/AvaloniaUI/Avalonia.Markup.Declarative/tree/master/src/AvaloniaNet472Test
it looks like even @binding syntax is working.
![image](https://user-images.githubusercontent.com/2227312/151637392-2f4a8ff9-82e2-411f-9f44-c2eabc11d258.png)

Can you try that sample and let me know if it works for you?

**Comment by tebjan** [comment]
it seems to use the old project format: https://github.com/AvaloniaUI/Avalonia.Markup.Declarative/blob/master/src/AvaloniaNet472Test/AvaloniaNet472Test.csproj

that might not work in our solution, but I'll try to migrate it to the new format.

**Comment by tebjan** [comment]
I tried to get it to work with VS 2019, but again I have only a white window... 

https://github.com/tebjan/Avalonia.Markup.Declarative/tree/dev/net472-compatibility

but maybe it is best to wait for the binary release as nuget and then set up a project with the nuget reference. so no worries, this was only a short research topic and isn't urgent. I might try do download VS 2022 and build the binaries myself it i have time at the weekend. thanks for the quick reply!

**Comment by najak3d** [comment]
@tebjan - it's great to see you here!   Where you go, great things happen; this we know!

IMO, might be best just to do it in VS2022, and just do it once.   I'm biting that bullet now too.   I had been using Avalonia's 0.10.10 release from Nov 2021, but they're latest is all on VS2022/.NET6 now.   That seems to be the best way to make progress on an integration between Stride and Avalonia.

The stuff you are working on for Stride3D will all be .NET6.0 and VS2022 anyways, right?

**Comment by tebjan** [comment]
Yes, when integrating Avalonia into the Stride game engine, it will use .net6 and VS 2022.

but I was here to research whether we can wrap Avalonia for vvvv as UI library. and we are on .net framework and VS 2019 for at least a few months, if not most of the year.

but targeting framework shouldn't be a problem, as the short demo project of @gritsenko  was demonstrating.

**Comment by gritsenko** [comment]
Life is too short...
