### ISSUE TITLE
CompiledBindings

### ISSUE THREAD

**Issue by ivanjx** [AvaloniaUI/Avalonia.Markup.Declarative#30]
Provide an API to do bindings with CompiledBindings. Currently this library uses the standard `Binding`.

**Comment by gritsenko** [comment]
> Provide an API to do bindings with CompiledBindings. Currently this library uses the standard `Binding`.

I'm not sure how this can be implemented :(

**Comment by gritsenko** [comment]
Now I'm experimenting with using of IObservable.Subscribe instead of using standard Binding... so probably it will be acceptable solution, need some investigation yet

**Comment by gritsenko** [comment]
So now on views inherited from **ComponentBase** (**not** ViewBase - it's important) you can use following method to make two sided binding:

```
new Slider()
  .Value(() => LayerOpacity, val => 
      () => {
         LayerOpacity = val;
         StateHasChnaged(); //this line notifies other dependent controls to be updated
      });
```
