### ISSUE TITLE
Target 11.0.0 and not 11.0.1

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia.Markup.Declarative#32]
@gritsenko for Library authors its recommended to target 11.0.0 which is the guaranteed stable api contract.

If you update to 11.0.1 it excludes anyone still on 11.0.0 from using your library.

If you need bug fixes for you sample app, then your test app or sample should target the latest avalonia.. but the core library 11.0.0

I will get someone to add docs about this to Avalonia repo.

**Comment by gritsenko** [comment]
Thank you, @danwalmsley ! I'll fix it tonight
