### ISSUE TITLE
Hot reload only works in release build (Rider)

### ISSUE THREAD

**Issue by BaseCrusher** [AvaloniaUI/Avalonia.Markup.Declarative#33]
Hot reload does not work in Debug mode.

**Comment by gritsenko** [comment]
> Hot reload does not work in Debug mode.

Hey! Could you provide sample project where I can reproduce this bug?

**Comment by BaseCrusher** [comment]
I tried it with the sample projects of this repo.

**Comment by gritsenko** [comment]
just tired on Visual Studio 2022 debug mode with the sample projects and hot reload was working as expected

**Comment by BaseCrusher** [comment]
I haven't tested it with VS but with Rider. 
![30-08-2023_12-09-39](https://github.com/AvaloniaUI/Avalonia.Markup.Declarative/assets/12885003/b58d2959-e758-47d2-bbcd-bb3358d4dd9c)

**Comment by gritsenko** [comment]
@BaseCrusher hey! Can you try hot reload with the latest update?

**Comment by BaseCrusher** [comment]
@gritsenko I've just tested it. Sadly it is still not fixed. When running in debug, i can also see the console output for `ClearCache` and `UpdateApplication` but when running in debug, there is nothing.

**Comment by gritsenko** [comment]
@BaseCrusher I found out that bug was related to JetBrains own hot reload implementation, it's actually reloads c# code during debug, but it doesn't send any notification to HotReloadManager. So I added workaround for the Rider support

```c#
//init app
AppBuilder.Configure<Application>()
  .UseRiderHotReload() //this line adds watcher that checks, if Views were changed during debugging session
  .SetupWithLifetime(lifetime);
```

(It's not published as a nuget package yet, only in sources)

**Comment by BaseCrusher** [comment]
I tested it on my machine and I can confirm that it now works.

The only question for me is, if we should consider creating a ticket at JetBrains to align their behavior with what .Net is using.

**Comment by gritsenko** [comment]
I saw only this ticket about it. I think the problem is the same.

https://youtrack.jetbrains.com/issue/RIDER-110981/Blazor-hot-reloading-still-not-working.

I didn't send any ticket, so you can make one if you think it's necessary

**Comment by BaseCrusher** [comment]
Ok, I will create one. If there are updates, I will let you know. :)

Thank you anyway very much for the workaround.
