### ISSUE TITLE
When will be a Nuget package available for this project?

### ISSUE THREAD

**Issue by vessillo** [AvaloniaUI/Avalonia.Markup.Declarative#35]
I'm awaiting for a Nuget package for this library so as to be able to use it in a class for computer programming. Thank you.
This is a very beautiful work!

**Comment by Shadowblitz16** [comment]
Please upload this to nuget!
I hate xaml! I would love to learn how to use avalonia ui in a C#.

**Comment by amirhoseinadelfar** [comment]
@gritsenko please make nuget package, its really annoying to clone this project every time for a simple demo/tool project

**Comment by cleissonalves** [comment]
The Nuget Package is on this source for now: https://nuget-feed-nightly.avaloniaui.net/v3/index.json

You can check with: 

``bash
dotnet package search Avalonia.Markup.Declarative --source https://nuget-feed-nightly.avaloniaui.net/v3/index.json
``

And install to a project/solution with:

```bash
dotnet add package Avalonia.Markup.Declarative --source https://nuget-feed-nightly.avaloniaui.net/v3/index.json
```

I believe that after some time it might be release on the main Nuget source.

**Comment by gritsenko** [comment]
Now it's available on https://www.nuget.org/packages/Avalonia.Markup.Declarative
