### ISSUE TITLE
[Question] Missing Dock extension for controls under DockPanel?

### ISSUE THREAD

**Issue by fallenwood** [AvaloniaUI/Avalonia.Markup.Declarative#37]
When I am trying to add a DockPanel like this, I found there is no `.Dock(Dock)` extension for either Control or Style, nor finding similar usage in samples.

Could it be a lacking functionality of the project, or some exisitng usage that I missed in source code?

```csharp
new DockPanel()
      .LastChildFill(true)
      .Children(
          new TextBox().Dock(Dock.Left),
          new TextBox().Dock(Dock.Right),
          new TextBox().Dock(Dock.Left));
```

**Comment by gritsenko** [comment]
Hey, @fallenwood ! You're right, there wasn't such extension.
I just added it latest commit and the example tab in sample project as well
