### ISSUE TITLE
OnPointer extension methods return InputElement instead of Control. 

### ISSUE THREAD

**Issue by cleissonalves** [AvaloniaUI/Avalonia.Markup.Declarative#39]
```csharp
new Panel()
    .Children(
        //works
        new Button().OnClick((_) => DoSomething()),
        //error: cannot convert from 'Avalonia.Input.InputElement' to 'Avalonia.Controls.Control'
        new Button().OnPointerPressed((_) => DoSomething()) 
    );

void DoSomething(){}
```
The same error happens for every OnPointer extension method when it is used as the sample above.

Is this the intended behavior? I believe it would be more useful if the extension methods for them were defined as generic of TControl.

**Comment by gritsenko** [comment]
@cleissonalves Hey! Yeah you're right! Thanks for suggestion, fixed in [latest commit](https://github.com/AvaloniaUI/Avalonia.Markup.Declarative/commit/4531c5a17f290c9a366eced76b3496907bb01541)
