### ISSUE TITLE
"Dock" - class Name vs. Namespace Conflict - with Dock library.

### ISSUE THREAD

**Issue by najak3d** [AvaloniaUI/Avalonia.Markup.Declarative#4]
I am integrating your library with "Dock.Avalonia" which creates a namespace conflict for "Avalonia.Controls.Dock", as shown here.   The existence of the "Dock" namespace, confuses the compiler.    I can manually fix this by changing "Dock" to "Avalonia.Controls.Dock".

How do you think this should be fixed?   Perhaps the perpetrator is the Dock.Avalonia library itself, which has a namespace that now matches an Avalonia control type.

![image](https://user-images.githubusercontent.com/10914515/151744275-6753d1ac-1cbb-4518-9358-4e306eabd9fc.png)

The github for the "Dock" library is here, by @wieslawsoltes :
https://github.com/wieslawsoltes/Dock

**Should we reconsider the root namespace for this library, given this name conflict?**

**Comment by gritsenko** [comment]
Thanks! I'll take a look tonight

**Comment by gritsenko** [comment]
#7
