### ISSUE TITLE
Suggestion: Consider changing generated InputElementEventsExtensions to allow RoutingStrategies

### ISSUE THREAD

**Issue by cleissonalves** [AvaloniaUI/Avalonia.Markup.Declarative#46]
### Motivation

[Routing Strategies Docs](https://docs.avaloniaui.net/docs/concepts/input/routed-events#routing-strategies)

Some controls already have handlers for inputs like certain keys or pointer events. For example:

* Buttons: LeftClick with OnPointerPressed only works setting routing to RoutingStrategies.Tunnel;
* ListBox: Left/Right arrows with OnKeyDown also only works setting routing to RoutingStrategies.Tunnel;

### Current InputElementEventsExtensions

Generated Code [Here](https://github.com/AvaloniaUI/Avalonia.Markup.Declarative/blob/8aec038479c628b406c1de5f30639d2353e9f383/src/Avalonia.Markup.Declarative/ControlEventExtensions.Generated.cs#L430), and the code generation defined [Here](https://github.com/AvaloniaUI/Avalonia.Markup.Declarative/blob/8aec038479c628b406c1de5f30639d2353e9f383/src/Avalonia.Markup.Declarative.SourceGenerator/AvaloniaEventExtensionsGenerator.cs#L117)

```csharp
public static T OnKeyDown<T>(this T control, Action<KeyEventArgs> action) where T : InputElement => 
        control._setEvent((EventHandler<KeyEventArgs>) ((_, args) => action(args)), h => control.KeyDown += h);
```

### Proposed Implementation. 

[BasedOn NXUI](https://github.com/wieslawsoltes/NXUI/blob/38248467db0011218363bef3c27496fc29384365/src/NXUI/Generated/Extensions/InputElement.Extensions.g.cs#L685)

```csharp
public static T OnKeyDown<T>(this T control, Action<KeyEventArgs> action, RoutingStrategies routes = RoutingStrategies.Tunnel | RoutingStrategies.Bubble) where T : InputElement
{
    control.AddHandler(InputElement.KeyDownEvent, (_, args) => action(args), routes);
    return control;
}
```

The same for all the others InputElementEventsExtensions.

It would be an non breaking change, as the RoutingStrategies would be an optional paramenter.

Sorry for bothering you too much with new issues.

**Comment by gritsenko** [comment]
resloved in https://www.nuget.org/packages/Avalonia.Markup.Declarative/11.2.0-beta4
