### ISSUE TITLE
HyperlinkButton missing extensions

### ISSUE THREAD

**Issue by IvanJosipovic** [AvaloniaUI/Avalonia.Markup.Declarative#47]
This library is missing the extensions for the new HyperlinkButton Control.

**Comment by IvanJosipovic** [comment]
@gritsenko, when can we expect the next nuget release?

Also, im noticing this repo isnt set up with the nightly ci builds.

**Comment by gritsenko** [comment]
@IvanJosipovic yep, I have to manually add tag to publish into nightly nuget feed

> when can we expect the next nuget release?

I hope to finish with #40 and #42 on this week, test everything and then I'll ask @maxkatz6 to trigger the release job

**Comment by gritsenko** [comment]
and now HyperlinkButton should be in the latest nightly built nuget already

**Comment by gritsenko** [comment]
published to latest nuget 11.1.3
