### ISSUE TITLE
Source generators not working with TemplatedControl

### ISSUE THREAD

**Issue by tomall97** [AvaloniaUI/Avalonia.Markup.Declarative#48]
I'm using the NuGet package [Avalonia.Markup.Declarative v11.0.11](https://www.nuget.org/packages/Avalonia.Markup.Declarative/11.0.11), and the source generators aren't generating markup extensions for my custom templated controls. I also tried copying [MyCustomTemplatedControl.cs](https://github.com/AvaloniaUI/Avalonia.Markup.Declarative/blob/master/src/Samples/AvaloniaMarkupSample/MyCustomTemplatedControl.cs) from the samples folder, but it didn't work either.

**IDE:** Visual Studio 2022 (v17.10.4), VSCode (v1.91.1)

Thank you in advance.

**Comment by gritsenko** [comment]
Hey @tomasmalik! Source generator is processing only controls that implement `IDeclarativeViewBase` interface. So you should add it to your class declaration.

```csharp
public class MyCustomTemplatedControl : TemplatedControl, IDeclarativeViewBase
{
...
}
```
