### ISSUE TITLE
Requesting Null Check for "With" extension

### ISSUE THREAD

**Issue by najak3d** [AvaloniaUI/Avalonia.Markup.Declarative#5]
If we can please do a null check on the "With" extension, as I sometimes send it a null Action delegate (I make this an optional argument).  Asking for code to look like this:

```c#
    public static TElement With<TElement>(this TElement control, Action<TElement> process)
    {
        process?.Invoke(control);
        return control;
    }
```

**Comment by Gillibald** [comment]
The action isn't optional. This does nothing without it and passing null to it is an error on the caller.

**Comment by najak3d** [comment]
> The action isn't optional. This does nothing without it and passing null to it is an error on the caller. This should throw in that case.

Please allow me to clarify my use-case.  I have a factory method that initializes a Label via Fluent-Pattern, that looks like this, where 'initMethod' is *optional*  (defaults to NULL):

```c#
						yield return new Label()
							.Content(text)
							**.With(initMethod)**
							.Foreground(OutlineBrush)
							.Margin(x, y, 0, 0)
							.FontSize(FontSize);

```

If "With" is going to throw on "initAction == null", then I will be forced to ugly-up my code, like this:

```c#
						return new Label()
							.Content(text)
							**.With(initMethod ?? new Action<Label>((label) => { }))**
							.Foreground(OutlineBrush)
							.Margin(x, y, 0, 0)
							.FontSize(FontSize);
```

It seems sensible to me that if you call "label.With(null)", that it would simply do nothing, as this reads like plain language:

     "With Nothing, does nothing".  
    (I gave this method nothing to do; and it simply did nothing, as should be expected.)

I'd much prefer our Fluent-Pattern to be forgiving for sensible scenarios like this one, and avoid having to do Null-checks in the C# composition code.

**Comment by najak3d** [comment]
@gritsenko :  Thank you for the short-hand, "(_ => {})".   We're still getting acclimated to C#7+ shorthand.

I do realize I can create my own extensions, but was hoping the "default package" that Avalonia provides would be more reusable without having to augment it, to achieve a more desirable syntax.

In Fluent-Syntax, there's no way to "omit the call to 'With'"; it will be called regardless of whether or not you have an Action to execute.  I think it is less-intuitive and less-convenient to have to suffix all of your calls with " ?? (_ => {})"  than it is too simply do as the call instructs - "With Nothing, does nothing".

**Comment by gritsenko** [comment]
Will be added with #7
