### ISSUE TITLE
 how to use treeview in  Csharp Markup - Avalonia

### ISSUE THREAD

**Issue by blackholeearth** [AvaloniaUI/Avalonia.Markup.Declarative#75]
hello how can i  make treeview  show any thing. on screen??

currently treeview looks empty   there is a white   empy rectangle space. 

 "which i know it belongs to treeview . (cuz i set height,width = 50,100  )"
 

````csharp    

Nodes = new ObservableCollection<Node>
{
    new Node("Animals", new ObservableCollection<Node>
    {
        new Node("Mammals", new ObservableCollection<Node>
        {
            new Node("Lion"), new Node("Cat"), new Node("Zebra")
        })
    })
};

 public ObservableCollection<Node> Nodes { get; set; }

   //code attached to the  build =>
       
          new TreeView() { 
               ItemsSource = Nodes, 
              // ItemTemplate =  new FuncTreeDataTemplate<Node>(,) {  }, 
               Width=50, Height=100},
              new Label().Content("my name is label"),
              new Button().Content("clickme")`
````

----
please keep the love in your heart for CS as UI lang. 
  (even android world is doing the same , they got sick of it. got back to all in code -  compose all the way)

 
 such a nice language and sytax is wasting away,  yet people dabbling in the xaml mud.. 

may  peace be upon you.

**Comment by gritsenko** [comment]
@blackholeearth hey! I added an example of adding treeview control [here](https://github.com/AvaloniaUI/Avalonia.Markup.Declarative/blob/master/src/Samples/AvaloniaMarkupSample/TreeViewSampleView.cs)

```csharp
                new TreeView()
                    .HorizontalAlignment(HorizontalAlignment.Center)
                    .ItemsSource(Nodes)
                    .ItemTemplate(
                        new FuncTreeDataTemplate<Node>(
                            (n, _) => new TextBlock().Text(n.Name),
                            n => n.Children)
                    )
```
