### ISSUE TITLE
Requesting Examples of using DynamicResources and Themes/Styles

### ISSUE THREAD

**Issue by najak3d** [AvaloniaUI/Avalonia.Markup.Declarative#9]
This is taken from Avalonia UI discussion Thread here:
[https://github.com/AvaloniaUI/Avalonia/discussions/7654](https://github.com/AvaloniaUI/Avalonia/discussions/7654)

We're trying to figure out how to do all things equivalent in Declarative mode to match what is currently done in XAML, and are currently stuck on the concept of DynamicResource (and styles in general).

Here's the XAML line:
Foreground="{DynamicResource DockThemeForegroundBrush}"

How in C# is the best way to bind our Foreground brush to the "DockThemeForegroundBrush"?

In general, I imagine that we'll continue to use the various AXAML-defined Themes (Fluent, Default, etc). So when using C#, what is the best way to make apply these themes' values?

Also then comes the concept of doing things like setting FontFamily based on string value, such as AXAML like this:

    FontFamily="Segoe UI, SF Pro Display, Noto Sans, Cantarel"
This does some sort mysterious of resource lookup by string key. What is a C# equivalent string search?

===
We're requesting the addition of sample code that demonstrates the answers to these concerns.

**Comment by najak3d** [comment]
Pasted from the other thread, here's the solution I have so far:
===
So I've converted this progress into Markup.Declarative extensions, which now looks like this:

First I created a reusable method to be called from each Extension method per assignable Property:
```c#
    public static TControl _setResource<TControl, TResource>(this TControl control, string resourceKey, Action<TResource> setAction)
    {
        object resourceObj;
        if (Application.Current.Styles.TryGetResource(resourceKey, out resourceObj))
        {
            if (resourceObj is TResource resource)
                setAction(resource);
        }
        return control;
    }
```

And here are two examples of individual Extension Methods that will now assign the Resource specified by the Key:
```c#
public static T Foreground<T>(this T control, string resourceKey) where T : TemplatedControl
=> control._setResource(resourceKey, (IBrush brush) => control.Foreground = brush);

public static T Foreground<T>(this T control, string resourceKey) where T : TemplatedControl
=> control._setResource(resourceKey, (IBrush brush) => control.Foreground = brush);

```

And now the UI composition code simply looks like this:
```c#
            window.Foreground("DockThemeForegroundBrush")
                .BorderBrush("DockThemeBorderLowBrush");
```

Sweet, yes?

Next step -  I think we need to make this Bindable, so that it responds to Mode/style changes to the App.

**Comment by najak3d** [comment]
Suggesting that we also permit Fonts to be assigned by font name, like this:

public static T FontFamily<T>(this T control, string fontName) where T : TemplatedControl
=> control._set(() => control.FontFamily = new FontFamily(null, fontName));

**Comment by gritsenko** [comment]
I don't like the idea to have String id's for resources. For now I'm placing resouces into static class like this:

```csharp
public static class StaticResources
{
    public static class Colors
    {
        public static Color PanelsBackgroundColor { get; } = "#4a525c".ToColor();
        public static Color MainBackgroundColor { get; } = "#2d2d2f".ToColor();
    }

    public static class Brushes
    {
        public static Brush SelectedHighlighterBrush { get; } = Colors.MyAccentColor.ToBrush();
        public static Brush AccentBrush { get; } = Colors.MyAccentColor.ToBrush();
    }
  }
}
```

then consume in in my views:
```csharp
  new Border()
    .BorderBrush(StaticResources.Brushes.SelectedHighlighterBrush)
    .Background(StaticResources.Brushes.SelectedItemBrush)
```

**Comment by najak3d** [comment]
I also don't like "string-based keys" and prefer something that hooks up at compile-time, like your example.  However, for this library to be a success, IMO, it needs to do a better job of bridging the gap between XAML methods and C#.  In this way, we should be able to consume existing AXAML-based Themes/Styles.

If someone wants to convert part of their UI to C#, they're still obligated to make use of the same Themes as the rest of the app, and therefore will need to bind by AXAML string keys.

I would love to see all of the AXAML themes/styles we have now converted to C# notation entirely.  I have some ideas on how to head in that direction.

So I think it's vital to add the Extensions which permit binding to AXAML resource string keys, to make it easy for someone to employ C# composition alongside AXAML-based views.

== Regarding the All-C# Approach ===
I think the best way to achieve this is to make it non-static, so that you can employ a base-class or interfaces to make it skinnable, via a "C# plugin".  Derived classes can override the members for each style, and so you just instantiate the class that has your selected theme/style.   To change themes run-time, just swap the class that is plugged in.

I'd really like to see this C# project become "equally capable" as the AXAML, because once it is -- it'll take off like a rocket.

**Comment by najak3d** [comment]
If you are OK with me doing some of this work, I can do that.  

I just need to know if you are wanting to take this library in the following directions:
1. Add bindings to Resource Keys (e.g. Background("{resourceKeyForBrush}")).

2. Do you want for this to be auto-reskinnable run-time?  (or will we require a restart?)  (e.g. if you change Theme from Fluent to Default, will it auto-rebuild the entire UI with the new theme?)

3. Are you interested in having C#-based Themes?  (starting with Fluent and Default)


===
I'm learning more as I'm going through the DockDemo now and ridding the pages/views of AXAML, and replacing it with C#.

**Comment by najak3d** [comment]
If you are averse to overloading the Extensions with "ResourceKey" bindings, we could do one of several things, that I can think of now:

1. Added "Key" suffix to each extension method,  e.g. ForegroundKey("{key}")

2. Or create a 2nd namespace for this, called something like "namespace Avalonia.Markup.Declarative.Resourced;"

3. Combination of 1 & 2. (use different namespace, and suffix methods with "Key").

**Comment by ivanjx** [comment]
these are my extensions:
```csharp
    public static T DynamicResource<T>(this T control, AvaloniaProperty prop, object resourceKey) where T : Control
    {
        control[!prop] = new DynamicResourceExtension(resourceKey);
        return control;
    }

    public static Style DynamicResource(this Style style, AvaloniaProperty prop, object resourceKey)
    {
        style.Setters.Add(new Setter()
        {
            Property = prop,
            Value = new DynamicResourceExtension(resourceKey)
        });
        return style;
    }
```

usage:
```csharp
control.DynamicResource(Button.BackgroundProperty, "ThemeAccentBrush")
```
```csharp
new Style(s => s.OfType<Button>())
    .DynamicResource(Button.BackgroundProperty, "ThemeAccentBrush"),
```

**Comment by gritsenko** [comment]
> these are my extensions:
> 
> ```cs
>     public static T DynamicResource<T>(this T control, AvaloniaProperty prop, object resourceKey) where T : Control
>     {
>         control[!prop] = new DynamicResourceExtension(resourceKey);
>         return control;
>     }
> 
>     public static Style DynamicResource(this Style style, AvaloniaProperty prop, object resourceKey)
>     {
>         style.Setters.Add(new Setter()
>         {
>             Property = prop,
>             Value = new DynamicResourceExtension(resourceKey)
>         });
>         return style;
>     }
> ```
> 
> usage:
> 
> ```cs
> control.DynamicResource(Button.BackgroundProperty, "ThemeAccentBrush")
> ```
> 
> ```cs
> new Style(s => s.OfType<Button>())
>     .DynamicResource(Button.BackgroundProperty, "ThemeAccentBrush"),
> ```

Actually following code is working as well:
```cs
                                new TextBlock()
                                    .Ref(out var textBlock)
                                    .Padding(12)
                                    .FontSize(30)
                                    .HorizontalAlignment(HorizontalAlignment.Center)
                                    .Foreground(new DynamicResourceExtension("SystemAccentColor"))
                                    .Text("Hello Hot Reload!"),
```

since DynamicResourceExtension is Binding

so I'm not sure if we really need extra extension

**Comment by Shadowblitz16** [comment]
Can this be reopened? 
Strings don't get autocomplete, you guys should use some sort of code generation.
